export const SET_GOODS_FILTER = 'SET_GOODS_FILTER';
export const SET_GOODS_COLORS_ARRAY = 'SET_GOODS_COLORS_ARRAY';

export const GET_GOODS_REQUEST = 'GET_GOODS_REQUEST';
export const GET_GOODS_SUCCESS = 'GET_GOODS_SUCCESS';
export const GET_GOODS_ERROR = 'GET_GOODS_ERROR';

export const SET_SORTING_DIRECTION = 'SET_SORTING_DIRECTION'

export const SET_MIN_PRICE_VALUE = 'SET_MIN_PRICE_VALUE';
export const SET_MAX_PRICE_VALUE = 'SET_MAX_PRICE_VALUE';